sudo: required
services:
  - docker

before_install:
  - docker build -t nvracar/react-app -f Dockerfile.dev .

script:
  - docker run nvracar/react-app npm run test -- --coverage --watchAll=false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
